// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.906
package pages

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import (
	"encoding/json"
	"raevtar/internal/model"
)

func MetricCharts(metrics []model.ServerMetric) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<div class=\"grid gap-6 md:grid-cols-2 mt-8\"><div class=\"nb-card bg-card p-5\"><h3 class=\"text-sm font-black uppercase text-muted mb-4\">CPU Usage (%)</h3><canvas id=\"cpuChart\" class=\"w-full h-48\" role=\"img\" aria-label=\"CPU Usage Chart\"></canvas></div><div class=\"nb-card bg-card p-5\"><h3 class=\"text-sm font-black uppercase text-muted mb-4\">RAM Usage (MB)</h3><canvas id=\"ramChart\" class=\"w-full h-48\" role=\"img\" aria-label=\"RAM Usage Chart\"></canvas></div></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = renderChartScript(metrics).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

func getChartData(metrics []model.ServerMetric) string {
	type ChartPoint struct {
		T string  `json:"t"`
		C float64 `json:"c"`
		R float64 `json:"r"`
	}

	// Reverse metrics to get chronological order
	data := make([]ChartPoint, 0, len(metrics))
	for i := len(metrics) - 1; i >= 0; i-- {
		m := metrics[i]
		data = append(data, ChartPoint{
			T: m.RecordedAt.Format("15:04:05"),
			C: m.CPUPercent,
			R: m.RAMUsedMB,
		})
	}

	b, _ := json.Marshal(data)
	return string(b)
}

func renderChartScript(metrics []model.ServerMetric) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var2 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var2 == nil {
			templ_7745c5c3_Var2 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "<script type=\"text/javascript\">\r\n\t\t(function() {\r\n\t\t\tconst data = JSON.parse(document.getElementById('chart-data-json').textContent);\r\n\t\t\tconst labels = data.map(p => p.t);\r\n\t\t\tconst cpuData = data.map(p => p.c);\r\n\t\t\tconst ramData = data.map(p => p.r);\r\n\r\n\t\t\tconst chartOptions = {\r\n\t\t\t\tresponsive: true,\r\n\t\t\t\tmaintainAspectRatio: false,\r\n\t\t\t\tanimation: false,\r\n\t\t\t\tscales: {\r\n\t\t\t\t\ty: { beginAtZero: true, grid: { color: '#2D3748', lineWidth: 1 } },\r\n\t\t\t\t\tx: { grid: { display: false } }\r\n\t\t\t\t},\r\n\t\t\t\tplugins: { legend: { display: false } }\r\n\t\t\t};\r\n\r\n\t\t\tnew Chart(document.getElementById('cpuChart'), {\r\n\t\t\t\ttype: 'line',\r\n\t\t\t\tdata: {\r\n\t\t\t\t\tlabels: labels,\r\n\t\t\t\t\tdatasets: [{\r\n\t\t\t\t\t\tdata: cpuData,\r\n\t\t\t\t\t\tborderColor: '#FACC15',\r\n\t\t\t\t\t\tborderWidth: 3,\r\n\t\t\t\t\t\tpointRadius: 0,\r\n\t\t\t\t\t\ttension: 0.1,\r\n\t\t\t\t\t\tfill: false\r\n\t\t\t\t\t}]\r\n\t\t\t\t},\r\n\t\t\t\toptions: chartOptions\r\n\t\t\t});\r\n\r\n\t\t\tnew Chart(document.getElementById('ramChart'), {\r\n\t\t\t\ttype: 'line',\r\n\t\t\t\tdata: {\r\n\t\t\t\t\tlabels: labels,\r\n\t\t\t\t\tdatasets: [{\r\n\t\t\t\t\t\tdata: ramData,\r\n\t\t\t\t\t\tborderColor: '#2D3748',\r\n\t\t\t\t\t\tborderWidth: 3,\r\n\t\t\t\t\t\tpointRadius: 0,\r\n\t\t\t\t\t\ttension: 0.1,\r\n\t\t\t\t\t\tfill: false\r\n\t\t\t\t\t}]\r\n\t\t\t\t},\r\n\t\t\t\toptions: chartOptions\r\n\t\t\t});\r\n\t\t})();\r\n\t</script><script id=\"chart-data-json\" type=\"application/json\">\r\n\t\t{ templ.Raw(getChartData(metrics)) }\r\n\t</script>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
